# Generated by Django 5.1.6 on 2025-02-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("fitness_admin", "Trainer")],
                default="user",
                max_length=20,
            ),
        ),
    ]
