# Generated by Django 5.1.6 on 2025-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_remove_customuser_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="workout_duration",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
