# Generated by Django 5.1.6 on 2025-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_workoutplan_workout_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="workout_thumbnails/"),
        ),
    ]
