# Generated by Django 5.1.6 on 2025-03-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_workoutplan_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Step order in the guide"
                    ),
                ),
                (
                    "guide",
                    models.TextField(help_text="Guide description for this step"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="workout_steps/"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=5, help_text="Duration for this step in minutes"
                    ),
                ),
                ("youtube_link", models.URLField(blank=True, null=True)),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="user_app.workoutplan",
                    ),
                ),
            ],
        ),
    ]
