# Generated by Django 5.1.6 on 2025-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_workoutstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="steps",
            field=models.JSONField(
                blank=True,
                help_text='List of steps for the workout. Format: [{"order": number, "guide": "instruction", "duration": minutes, "image": "URL", "youtube_link": "URL"}, ...]',
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="WorkoutStep",
        ),
    ]
