# Generated by Django 5.1.6 on 2025-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_workoutplan_steps_delete_workoutstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="success_stories/")),
            ],
        ),
    ]
