# Generated by Django 5.1.6 on 2025-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0008_successstory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="price",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="price",
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium")],
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="directions",
            field=models.JSONField(
                blank=True,
                help_text="List of directions. Format: [{'step': 1, 'instruction': 'Wash the apple'}, ...]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meal_images/"),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="ingredients",
            field=models.JSONField(
                blank=True,
                help_text="List of ingredients. Format: [{'name': '15 almonds', 'alternative': 'hazelnuts'}, ...]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="successstory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="success_stories/"
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="workout_thumbnails/"
            ),
        ),
    ]
