# Generated by Django 5.1.6 on 2025-03-24 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_remove_mealplan_price_remove_workoutplan_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="meal_plan",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_for",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="workout_plan",
        ),
    ]
