# Generated by Django 5.1.6 on 2025-03-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_app",
            "0010_remove_payment_meal_plan_remove_payment_payment_for_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription_type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium"), ("none", "None")],
                default="none",
                max_length=10,
            ),
        ),
    ]
