# Generated by Django 5.1.6 on 2025-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_customuser_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
