# Generated by Django 5.1.6 on 2025-06-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_successstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/'),
        ),
    ]
