# Generated by Django 5.1.6 on 2025-08-09 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_successstory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AddField(
            model_name='successstory',
            name='advice_for_others',
            field=models.TextField(blank=True, help_text='Advice for others starting their fitness journey', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/after/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/before/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='biggest_achievement',
            field=models.CharField(blank=True, help_text='Single biggest achievement or milestone', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='category',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('fitness_journey', 'Fitness Journey'), ('lifestyle_change', 'Lifestyle Change'), ('health_recovery', 'Health Recovery'), ('strength_building', 'Strength Building')], default='fitness_journey', max_length=20),
        ),
        migrations.AddField(
            model_name='successstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successstory',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='in kg', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='diet_changes',
            field=models.TextField(blank=True, help_text='Key dietary changes made', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '6 months', '1 year', '18 weeks'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='successstory',
            name='key_challenges',
            field=models.TextField(blank=True, help_text='Main challenges faced during the journey', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='motivation',
            field=models.TextField(blank=True, help_text='What motivated this transformation', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='starting_weight',
            field=models.FloatField(blank=True, help_text='in kg', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successstory',
            name='weight_loss',
            field=models.CharField(blank=True, help_text="e.g., '25 lbs', '15 kg', 'No weight focus'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='workout_routine',
            field=models.TextField(blank=True, help_text='Brief description of workout routine followed', null=True),
        ),
    ]
