# Generated by Django 5.1.6 on 2025-08-09 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_successstory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exercise_type', models.CharField(blank=True, choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('plyometrics', 'Plyometrics'), ('powerlifting', 'Powerlifting'), ('stretching', 'Stretching')], db_index=True, max_length=50, null=True)),
                ('body_part', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('equipment', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20, null=True)),
                ('rating', models.FloatField(db_index=True, default=0.0)),
                ('rating_description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_compound', models.BooleanField(default=False, help_text='Is this a compound movement?')),
                ('is_unilateral', models.BooleanField(default=False, help_text='Is this a unilateral exercise?')),
                ('requires_spotter', models.BooleanField(default=False)),
                ('estimated_calories_per_minute', models.FloatField(default=0.0)),
                ('tags', models.JSONField(blank=True, help_text='Tags for better search and recommendations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'title'],
                'indexes': [models.Index(fields=['body_part', 'difficulty_level'], name='user_app_ex_body_pa_6aeb58_idx'), models.Index(fields=['equipment', 'exercise_type'], name='user_app_ex_equipme_29e7bf_idx'), models.Index(fields=['rating', '-created_at'], name='user_app_ex_rating_d765de_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_completed', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateTimeField(blank=True, null=True)),
                ('personal_best_weight', models.FloatField(blank=True, null=True)),
                ('personal_best_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('personal_best_time', models.DurationField(blank=True, null=True)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, help_text="User's perceived difficulty (1-5)", null=True)),
                ('enjoyment_rating', models.PositiveSmallIntegerField(blank=True, help_text='How much user enjoys this exercise (1-5)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_completed', '-times_completed'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
