# Generated by Django 5.1.6 on 2025-08-13 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_exercise_userexerciseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='How long the workout took in minutes', null=True)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, help_text="User's perceived difficulty (1-5)", null=True)),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, help_text='How satisfied user was with the workout (1-5)', null=True)),
                ('notes', models.TextField(blank=True, help_text="User's notes about the workout session", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_history', to='user_app.workoutplan')),
            ],
            options={
                'verbose_name_plural': 'Workout History',
                'ordering': ['-completed_at'],
            },
        ),
    ]
