# Generated by Django 5.2.16 on 2026-07-18 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_workouthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=50)),
                ('days', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False, help_text='The plan the user is currently following')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
